# Generated by Django 6.0.5 on 2026-05-28 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название курса",
                        max_length=100,
                        verbose_name="Название курса",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        help_text="Загрузите превью курса",
                        upload_to="lessons/course_previews",
                        verbose_name="Превью",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Введите описание",
                        max_length=200,
                        verbose_name="Описание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название урока",
                        max_length=100,
                        verbose_name="Название урока",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        help_text="Загрузите превью урока",
                        upload_to="lessons/lesson_previews",
                        verbose_name="Превью",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Введите описание", verbose_name="Описание"
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        help_text="Введите ссылку на урок", verbose_name="Ссылка"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Выберите курс, к которому относится урок",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="lessons.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
