# Generated by Django 6.0.5 on 2026-05-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите превью курса",
                null=True,
                upload_to="lessons/course_previews",
                verbose_name="Превью",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите превью урока",
                null=True,
                upload_to="lessons/lesson_previews",
                verbose_name="Превью",
            ),
        ),
    ]
